### ISSUE TITLE
Unit tests are failing due to transpilation.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#1]
I'm not sure what the best solution is to fix these. It seems to be broken after we upgraded to typescript 1.5: https://github.com/sergeyt/karma-typescript-preprocessor/issues/30. 

I'll buy someone a beer if they fix this.

**Comment by sergeyt** [comment]
@niemyjski just try to prepare JS files with some gulp task for karma runner without use of preprocessor.

**Comment by niemyjski** [comment]
Yeah it's a lot of extra work but something we'll have to do
