### ISSUE TITLE
Error reported in vite3. x

### ISSUE THREAD

**Issue by DejaVuuuuuuu** [exceptionless/Exceptionless.JavaScript#114]
![QQ图片20221123151217](https://user-images.githubusercontent.com/35360899/203489956-fbebacde-3efb-4958-b0f3-bd01783b20d1.png)

**Comment by niemyjski** [comment]
@DejaVuuuuuuu those are all typescript files so it's kind of weird it's changing the extension to import those. I haven't used vite much, is there a setting for this? Also, what package of ours are you using? Do you have an easy way for us to reproduce this issue?

**Comment by niemyjski** [comment]
Hello,

I'm going to close this as we added a svelte example that uses the latest version of vite in the 2.0.1 release (https://github.com/exceptionless/Exceptionless.JavaScript/releases/tag/v2.0.1) and it's working. If you are still running into issues, please let us know.
