### ISSUE TITLE
Using ExceptionlessClient causes Node script not to exit

### ISSUE THREAD

**Issue by kareldonk** [exceptionless/Exceptionless.JavaScript#139]
If I create the following script in a file called `test.js`:

```
main();

async function main() {
    const client = require('exceptionless').ExceptionlessClient.default;
    client.config.apiKey = 'API_KEY_HERE';
}
```

and then run the command `node test.js` on the command line, the script runs and does not exit back to the command line. Why is this happening? I would expect execution to stop after the last line in the `main()` function. 
Currently this is causing lambda functions on AWS to continue to stay active when in fact they are finished running.

**Comment by niemyjski** [comment]
What version of the client are you using? This looks like the first version, I'd recommend using the latest version which solves this.

**Comment by kareldonk** [comment]
Version 1.6.4 as listed here: https://www.npmjs.com/package/exceptionless
Which version do you recommend using for nodejs and typescript projects?

**Comment by ejsmith** [comment]
Try this one: https://www.npmjs.com/package/@exceptionless/node

**Comment by ejsmith** [comment]
@niemyjski can we delist the old one?

**Comment by niemyjski** [comment]
@ejsmith I just deprecated it: https://www.npmjs.com/package/exceptionless

![image](https://github.com/exceptionless/Exceptionless.JavaScript/assets/1020579/adf7e5d6-65a3-43f0-9a39-938e853cd928)
