### ISSUE TITLE
Misleading docs for a custom client in react

### ISSUE THREAD

**Issue by pvrobays** [exceptionless/Exceptionless.JavaScript#150]
While upgrading to the exceptionless/react package, we implemented it as we found in the [docs](https://exceptionless.com/docs/clients/javascript/guides/react/):

```
import { ExceptionlessClient } from 'exceptionless/dist/exceptionless';
const config = {
  apiKey: "YOUR API KEY", 
  serverUrl: "YOUR SELF HOSTED URL",
  ...
};
const client = new ExceptionlessClient(config);
```

With this code however, the exceptionless client wouldn't send out new events.
Since the new API you need to call the `startup` function yourself. So the docs are actually missing the following part:

```
client.startup();
```

It may be useful for others to add this extra line to the example in the react docs.

**Comment by niemyjski** [comment]
I'll get this updated.

**Comment by niemyjski** [comment]
Thanks again for reporting this issue with our docs. I went through all the guides and updated them. Please let us know if you find any other issues. Please feel free to submit pr's as well!
