### ISSUE TITLE
Saving large amounts of events will cause server settings to be lost.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#19]
This occurs because the InMemoryStorage has a max size of 250 items... So if you queue a large amount of events, this will cause the server settings to be lost as the first item is removed.

@ejsmith I think this is also a bug with the .net client.

**Comment by ejsmith** [comment]
This really isn't a problem since it's only going to happen with the in memory implementation which will get reset when the app restarts anyway.
