### ISSUE TITLE
Add support for stringifying event data with a maxDepth

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.JavaScript#25]
I received some HTTP error 413 calls in the console log. After inspection why the event submission failed, I found out it was about the send in over 5MB of stuff while posting as little as 3 events.

In this case it was caused by the angular integration / feature reporting, based on ngRoute.
Path of the biggest chunks of data data are

```
data.@request.current.locals.$template
```

and also 

```
data.@request.next.locals.$template
```

$template should probably not be included in the events, but I'm not sure if there are others. Best idea might be to pick the properties that should be included, instead of keeping an exclusion list?

**Comment by niemyjski** [comment]
I wanted to provide additional information about the previous and next routes for debugging but this can be a huge problem if the route contains templates and large amounts of scope info like yours.  I almost think maybe we should be adding an overload for add object which takes a depth and an exclusion list and shrinks it so we only go two levels deep. What do you think about this?

**Comment by ejsmith** [comment]
Yeah, totally agreed that we need to add a max depth feature on the client. Also, the angular integration should add a global exclude for $template

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless.JavaScript/issues/37
