### ISSUE TITLE
Promises: Unhandled rejections

### ISSUE THREAD

**Issue by frankebersoll** [exceptionless/Exceptionless.JavaScript#32]
One big issue with exception handling in JavaScript is **Promises**: When you don't explicitly handle an error using a rejection callback, most Promise libraries provide global events like `Promise.onPossiblyUnhandledRejection` (bluebird.js), `Q.getUnhandledReasons` (Q.js) or `process.on('unhandledRejection)` (Node.js). Not subscribing to those events when using Promises probably contributes to many programmer errors staying unnoticed, as the application won't neccessarily terminate.

It would be cool if Exceptionless.js checked for the existence of such modules and events and created handlers that automatically submit the exceptions. While we do that, we should refactor all global exception handlers into implementations of an interface that can be added to the configuration like plugins.

Name proposals:
- IGlobalExceptionHandler
- IExceptionHook
- IExceptionSource

**Comment by ejsmith** [comment]
Seems like this can just be plugins for each technology. So you would wire up to Promise.onPossiblyUnhandledRejection and then submit the event from inside the handler. We are already doing something very similar here:

https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/src/integrations/angular.ts

**Comment by niemyjski** [comment]
The 2.0 client had support for unhandled rejections but I added an example and uncovered a few issues around types... you can reject anything. We now properly handle converting unknown types to error objects.
