### ISSUE TITLE
Improved Deduplication

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#44]
We should update the client to be more in line with the .NET client and support submitting the deduped count.

https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.4.0

**Comment by srijken** [comment]
And set the date to the max of the dates of the rolled up events

**Comment by niemyjski** [comment]
How's this coming along?

**Comment by niemyjski** [comment]
@srijken closing this
