### ISSUE TITLE
url parse is wrong

### ISSUE THREAD

**Issue by a26364177** [exceptionless/Exceptionless.JavaScript#79]
exceptionless.node.js 2076
 var protocol = (parsedHost.protocol === 'https' ? https : http);

url.parse(request.url).protocol always be 'https:'.

so self host https will be wrong.

**Comment by niemyjski** [comment]
That's picked up from the passed in from the configuration server url property. If that is https than it will always be sent as https, otherwise http request will be made. Does this resolve this issue?

**Comment by a26364177** [comment]
exceptionless.node.js 2059
var parsedHost = url.parse(request.url);
var protocol = (parsedHost.protocol === 'https' ? https : http);

url.parse will catch protocol as 'https:' not 'https'
so ervery https url will link to http.

**Comment by niemyjski** [comment]
Ahhh, do you have a link to the documentation for the parse that shows this? In my tests I was always getting the https client. Also what version of node are you using

**Comment by a26364177** [comment]
nodejs doc
https://nodejs.org/docs/latest/api/url.html#url_url_protocol

My nodeJs version is v8.9.0.

**Comment by niemyjski** [comment]
Thanks for reporting this, I'll work on getting out a release out in the morning.
