### ISSUE TITLE
Where i can find the log

### ISSUE THREAD

**Issue by jamilhaddadin** [exceptionless/Exceptionless.JavaScript#83]
The documentation is missing a very important aspect, where can we find the submitted data? (i.e. locally, another webservices that will take care of logging?)

**Comment by niemyjski** [comment]
I'm not sure what you mean by this. The client submits the events to the exceptionless server which stores the events in Elasticsearch. Does this help?

**Comment by jamilhaddadin** [comment]
aha I see, Cannot we have the data log stored somewhere as server side (I can have a restful service interface that can store the error details in a file system or event viewer)

**Comment by niemyjski** [comment]
It's only stored server side in elasticsearch. You can call the servers api to get events (https://github.com/exceptionless/Exceptionless/wiki/API-Usage)

**Comment by jamilhaddadin** [comment]
make sense! thanks a lot :-)
