### ISSUE TITLE
Recommended CDN is end of life

### ISSUE THREAD

**Issue by glaidler** [exceptionless/Exceptionless.JavaScript#90]
Hi, in the docs, the suggested CDN is rawgit.com; however when you view http://rawgit.com it suggests it will be shut down shortly.

I suggest you update the docs to provide a CDN which is not in danger of being shut down - e.g.

https://unpkg.com/exceptionless@1.5.5/dist/exceptionless.min.js

**Comment by niemyjski** [comment]
Thanks for logging this issue. I 100% agree. It would be nice to be on `cdnjs` and `jsdelivr`. Do you know exactly the spots where you saw this being listed as rawgit (was it the wiki and readme?)? Is there any chance you'd be willing to submit us to some of the cdn's and link any cdn pr's to here?

**Comment by glaidler** [comment]
We used the following page to configure.

https://github.com/exceptionless/Exceptionless.JavaScript/blob/4972b568fbb20aea289484da832f2c54364d45a9/README.md

Re. which CDN, unpkg was the first production-grade one I found that you publish to.  Happy to use whatever other one(s) you choose to publish to.

**Comment by niemyjski** [comment]
Thanks for reporting this, I just updated the readme with a cdn that works globally.
