### ISSUE TITLE
Import/Require From dist folder is confusing

### ISSUE THREAD

**Issue by polluterofminds** [exceptionless/Exceptionless.JavaScript#94]
Most JS libraries will handle importing or requiring packages like this: 

`import library from 'library'`;

or 

`const library = require('library');`

With Exceptionless, because the JS client is a monorepo, the developer has to remember to import from the library's `dist` folder. 

A better approach would be how other projects handle this like: 

`import exceptionless from '@exceptionless/node`

or 

`const exceptionless = require('@exceptionless/browser')`

**Comment by niemyjski** [comment]
We just merged in our 2.0 rewrite and I'll be updating the readme and then cutting a release. Is there any chance you could try out the 2.0.0-beta when we tag  it. We completely redid our packages based on this feedback.
